"""Compatibility facade for the agent-safe Codex backend client."""

from __future__ import annotations

from ._api_response import APIResponse, LegacyAPIResponse
from ._client import CodexClient, OpenAI
from ._exceptions import (
    APIConnectionError,
    APIError,
    APIResponseValidationError,
    APIStatusError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    ConflictError,
    InternalServerError,
    NotFoundError,
    OpenAIError,
    PermissionDeniedError,
    RateLimitError,
    UnprocessableEntityError,
)
from ._models import (
    CodexBaseModel,
    CompactedResponse,
    Model,
    ParsedResponse,
    Reasoning,
    ReasoningContext,
    ReasoningEffort,
    ReasoningSummary,
    Response,
    ResponseFormatJsonSchema,
    ResponseStreamEvent,
    ResponseUsage,
    ServiceTier,
    SyncPage,
    Verbosity,
)
from ._utils import CodexBackendUnsupportedParameterError, image_b64, image_url

__all__ = [
    "APIConnectionError",
    "APIError",
    "APIResponse",
    "APIResponseValidationError",
    "APIStatusError",
    "APITimeoutError",
    "AuthenticationError",
    "BadRequestError",
    "CodexBackendUnsupportedParameterError",
    "CodexBaseModel",
    "CodexClient",
    "CompactedResponse",
    "ConflictError",
    "InternalServerError",
    "LegacyAPIResponse",
    "Model",
    "OpenAI",
    "OpenAIError",
    "NotFoundError",
    "ParsedResponse",
    "PermissionDeniedError",
    "RateLimitError",
    "Reasoning",
    "ReasoningContext",
    "ReasoningEffort",
    "ReasoningSummary",
    "Response",
    "ResponseFormatJsonSchema",
    "ResponseStreamEvent",
    "ResponseUsage",
    "ServiceTier",
    "SyncPage",
    "UnprocessableEntityError",
    "Verbosity",
    "image_b64",
    "image_url",
]
